### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bloha** [bloha/rajce-dl#7]
# Roadmap

## Migration to TypeScript
All packages should be adapted, and JSDoc should be replaced with TSDoc.
- [ ] rajce-dl-sdk
- [ ] priority-queue
- [ ] observable
- [ ] native-protocol
- [ ] message-center
- [ ] native-messenger
- [ ] core-client
- [ ] native-application
- [ ] electron-gui

## Build system
- [ ] Do not re-download the same dependencies for each package
- [ ] Solve the problem with the uncovered core-client

## Architecture changes
- [ ] Separate Node.js logic from the native-application package
- [ ] The native application should become a daemon and be able to work standalone
- [ ] The RequestPool should use a queue to avoid DoS attacks
- [ ] Implement a global progress bar
- [ ] Implement a session progress bar
- [ ] Implement an ability to pause the download

## core-client
- [ ] Implement an ability to browse albums

## Command-line interface
- [ ] Implement the CLI (from scratch)

## Browser extension
- [ ] Adapt the code from the legacy project
- [ ] Inject a download button to the Rajce website
- [ ] Add support for Chrome

## Deno
The project should work with two platforms - Node.js and Deno.
- [ ] Implement native-application with Deno
- [ ] Implement GUI with Deno
- [ ] Implement CLI with Deno
